package com.mohamednader.shoponthego.Model.order

data class LineItemXX(
    val admin_graphql_api_id: String,
    val discount_allocations: List<DiscountAllocationXX>,
    val duties: List<Any>,
    val fulfillable_quantity: Int,
    val fulfillment_service: String,
    val fulfillment_status: Any,
    val gift_card: Boolean,
    val grams: Int,
    val id: Long,
    val name: String,
    val price: String,
    val price_set: PriceSetXXXX,
    val product_exists: Boolean,
    val product_id: Long,
    val properties: List<Property>,
    val quantity: Int,
    val requires_shipping: Boolean,
    val sku: String,
    val tax_lines: List<TaxLineXX>,
    val taxable: Boolean,
    val title: String,
    val total_discount: String,
    val total_discount_set: TotalDiscountSetXX,
    val variant_id: Long,
    val variant_inventory_management: String,
    val variant_title: String,
    val vendor: Any
)